module.exports = {
  rules: {
    'no-console': 1,
    "for-direction" : 2,
    "no-compare-neg-zero" : 2,
    "no-cond-assign": 2 ,
    "no-constant-condition" : 2 ,
    "no-dupe-args" : 2,
    "no-dupe-keys" : 2,
    "no-duplicate-case" : 2 ,
    "no-empty" : 2,
    "no-empty-character-class" : 2,
    "no-ex-assign" : 2,
    "no-extra-boolean-cast":1,
    "no-extra-parens" : 1,
    "no-extra-semi" : 2,
    "no-func-assign" : 2,
    "no-inner-declarations" : 1,
    "no-invalid-regexp" : 2,
    "no-obj-calls" : 2,
    "no-regex-spaces" : 1,
    "no-template-curly-in-string" : 2,
    "no-unreachable" : 2,
    "no-unsafe-negation" : 2,
    "use-isnan" : 1,
    "valid-typeof" : 2,

    "block-scoped-var" : 1,
    "curly" : ["warn" , "multi-line"],
    "default-case" : 1,
    "eqeqeq" : ["error", "always", {"null": "ignore"}] ,
    "no-lone-blocks" : 1 ,
    "no-loop-func" : 1,
    "no-else-return" : 1,
    "no-empty-function" : ["error", {"allow": ["functions"]}],
    "no-empty-pattern" : 1 ,
    "no-fallthrough" : 2,
    "no-floating-decimal" : 1,
    "no-global-assign" : 2,
    "no-invalid-this" : 1,
    "no-lone-blocks" : 2,
    "no-loop-func" : 2,
    "no-magic-numbers" : 0,
    "no-multi-spaces" : 2,
    "no-new-wrappers" : 2,
    "no-redeclare" : 2,
    "no-return-assign" : 2,
    "no-self-assign" : 2,
    "no-self-compare" : 2,
    "no-throw-literal" : 2,
    "no-unmodified-loop-condition" : 2,
    "no-unused-expressions" : 0,
    "no-useless-concat" : 2,
    "no-useless-escape" : 2,
    "no-useless-return" : 2,

    "no-undef" : 2 ,
    "no-undef-init" : 2 ,
    "no-unused-vars" : 2,
    "no-undefined" : 0,
    "no-use-before-define" : 0 ,


    "array-bracket-spacing" : 1 ,
    "block-spacing" : 1,
    "brace-style" : 1,
    "comma-dangle": ["warn", {
      "arrays": "never",
      "objects": "never",
      "imports": "never",
      "exports": "never",
      "functions": "ignore"
    }],
    "comma-spacing": ["warn", {
      "before": false ,
      "after" : true
    }],
    "computed-property-spacing" : 1,
    "func-call-spacing" : 1,
    "function-paren-newline" : 1,
    "indent" : 1 ,
    "key-spacing" : ["warn", {
      "beforeColon": false,
      "afterColon": true
    }],
    "keyword-spacing" : ["error", {
      "before": false,
      "after": true
    }],
    "max-depth" : 1,
    "new-cap" : 1,
    "new-parens" : 1,
    "newline-per-chained-call" : ["warn" , {
      "ignoreChainWithDepth": 3
    }],
    "no-lonely-if": 1,
    "no-mixed-spaces-and-tabs" : 1,
    "no-multiple-empty-lines" : 1,
    "no-trailing-spaces" : 1,
    "no-whitespace-before-property" : 1,
    "nonblock-statement-body-position" : 1,
    "object-curly-spacing" : ["warn", "always"],
    "operator-assignment" : 1,
    "padded-blocks" : ["warn","never"],
    "quote-props" : ["warn", "consistent"],
    "quotes" : ["warn" ,"single"],
    "semi": 1 ,
    "semi-spacing" : 1,
    "semi-style" : 1,
    "space-before-blocks":1,
    "space-before-function-paren" : 1,
    "space-in-parens": ["warn", "never"],
    "space-infix-ops" : 1,
    "switch-colon-spacing" : 1,
    "wrap-regex" : 1,

    "constructor-super" : 2 ,
    "no-const-assign" : 2,
    "no-dupe-class-members" : 2,
    "no-duplicate-imports" : 2,
    "no-useless-computed-key" :2,
    "no-useless-rename" : 2,
    "prefer-const" : 2
  }
};
